id: zipkin-config-exposure
name: Zipkin Configuration - Exposure
severity: low
confidence: tentative
description: Detected the exposure of the Zipkin configuration endpoint (/config.json), which may reveal internal configuration
  details.
reference: https://zipkin.io/
tags:
- zipkin
- exposure
- config
requests:
- method: GET
  path: /config.json
  matchers: &id001
  - type: body
    words:
    - '"queryLimit":'
    - '"environment":'
    - '"instrumented":'
    - '"defaultLookback":'
  - type: header
    words:
    - application/json
  - type: status
    status:
    - 200
  condition: and
- method: GET
  path: /zipkin/config.json
  matchers: *id001
  condition: and
