//! HTML report generation using Tera templates

use crate::error::Result;
use crate::models::{Finding, ScanResult, Severity};
use serde::Serialize;
use std::collections::HashMap;
use std::path::Path;
use tera::{Context, Tera};
use tracing::info;

/// An attack scenario generated from findings
#[derive(Serialize, Clone)]
struct AttackScenario {
    title: String,
    description: String,
    impact: String,
    likelihood: String,
    severity_class: String,
}

/// A remediation step generated from findings
#[derive(Serialize, Clone)]
struct RemediationStep {
    priority: String,
    finding: String,
    action: String,
    effort: String,
    severity_class: String,
}

/// All translatable strings for the HTML report
#[derive(Serialize, Clone)]
struct ReportLabels {
    // Header
    subtitle: &'static str,
    // Info bar
    started: &'static str,
    finished: &'static str,
    duration_label: &'static str,
    requests: &'static str,
    modules_label: &'static str,
    // Executive summary
    executive_summary: &'static str,
    risk_suffix: &'static str,
    // Severity labels
    critical: &'static str,
    high: &'static str,
    medium: &'static str,
    low: &'static str,
    info_label: &'static str,
    // Categories
    findings_by_category: &'static str,
    // Attack scenarios
    attack_scenarios: &'static str,
    attack_scenarios_intro: &'static str,
    impact_label: &'static str,
    likelihood_label: &'static str,
    // Remediation
    remediation_plan: &'static str,
    remediation_intro: &'static str,
    priority: &'static str,
    finding_label: &'static str,
    action_required: &'static str,
    effort: &'static str,
    // Diff
    differential_analysis: &'static str,
    new_label: &'static str,
    resolved_label: &'static str,
    persisting_label: &'static str,
    new_findings_regressions: &'static str,
    resolved_findings_fixed: &'static str,
    // Findings
    findings_title: &'static str,
    evidence: &'static str,
    request_label: &'static str,
    response_label: &'static str,
    recommendation: &'static str,
    no_findings: &'static str,
    no_findings_desc: &'static str,
    // Footer
    generated_by: &'static str,
}

impl ReportLabels {
    fn en() -> Self {
        Self {
            subtitle: "Web Security Scan Report",
            started: "Started:",
            finished: "Finished:",
            duration_label: "Duration:",
            requests: "Requests:",
            modules_label: "Modules:",
            executive_summary: "Executive Summary",
            risk_suffix: "Risk",
            critical: "Critical",
            high: "High",
            medium: "Medium",
            low: "Low",
            info_label: "Info",
            findings_by_category: "Findings by Category",
            attack_scenarios: "Attack Scenarios",
            attack_scenarios_intro: "Based on the findings detected, the following attack scenarios are possible against this application:",
            impact_label: "Impact:",
            likelihood_label: "Likelihood:",
            remediation_plan: "Remediation Plan",
            remediation_intro: "Prioritized actions to address the findings. P0 items should be resolved before production deployment.",
            priority: "Priority",
            finding_label: "Finding",
            action_required: "Action Required",
            effort: "Effort",
            differential_analysis: "Differential Analysis",
            new_label: "New",
            resolved_label: "Resolved",
            persisting_label: "Persisting",
            new_findings_regressions: "New Findings (Regressions)",
            resolved_findings_fixed: "Resolved Findings (Fixed)",
            findings_title: "Findings",
            evidence: "Evidence",
            request_label: "Request",
            response_label: "Response",
            recommendation: "Recommendation:",
            no_findings: "No findings detected",
            no_findings_desc: "The scan completed without identifying security issues.",
            generated_by: "Generated by Argos Panoptes",
        }
    }

    fn es() -> Self {
        Self {
            subtitle: "Reporte de Seguridad Web",
            started: "Inicio:",
            finished: "Fin:",
            duration_label: "Duración:",
            requests: "Peticiones:",
            modules_label: "Módulos:",
            executive_summary: "Resumen Ejecutivo",
            risk_suffix: "Riesgo",
            critical: "Crítico",
            high: "Alto",
            medium: "Medio",
            low: "Bajo",
            info_label: "Info",
            findings_by_category: "Hallazgos por Categoría",
            attack_scenarios: "Escenarios de Ataque",
            attack_scenarios_intro: "Basado en los hallazgos detectados, los siguientes escenarios de ataque son posibles contra esta aplicación:",
            impact_label: "Impacto:",
            likelihood_label: "Probabilidad:",
            remediation_plan: "Plan de Remediación",
            remediation_intro: "Acciones priorizadas para abordar los hallazgos. Los items P0 deben resolverse antes del despliegue a producción.",
            priority: "Prioridad",
            finding_label: "Hallazgo",
            action_required: "Acción Requerida",
            effort: "Esfuerzo",
            differential_analysis: "Análisis Diferencial",
            new_label: "Nuevos",
            resolved_label: "Resueltos",
            persisting_label: "Persistentes",
            new_findings_regressions: "Nuevos Hallazgos (Regresiones)",
            resolved_findings_fixed: "Hallazgos Resueltos (Corregidos)",
            findings_title: "Hallazgos",
            evidence: "Evidencia",
            request_label: "Petición",
            response_label: "Respuesta",
            recommendation: "Recomendación:",
            no_findings: "No se detectaron hallazgos",
            no_findings_desc: "El escaneo se completó sin identificar problemas de seguridad.",
            generated_by: "Generado por Argos Panoptes",
        }
    }

    fn for_lang(lang: &str) -> Self {
        match lang {
            "es" => Self::es(),
            _ => Self::en(),
        }
    }
}

/// Generates attack scenarios from findings based on CWE patterns
fn generate_attack_scenarios(findings: &[Finding], lang: &str) -> Vec<AttackScenario> {
    let mut scenarios = Vec::new();
    let mut seen = std::collections::HashSet::new();

    let cwes: Vec<String> = findings
        .iter()
        .filter_map(|f| f.cwe_id.as_ref())
        .cloned()
        .collect();

    let is_es = lang == "es";

    if cwes.iter().any(|c| c == "CWE-319") && !seen.contains("mitm") {
        seen.insert("mitm");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Ataque Man-in-the-Middle (Intercepción de Red)".into(),
                description: "Sin HSTS, la primera conexión del navegador puede ser interceptada. Un atacante en la misma red (WiFi, LAN corporativa) puede usar herramientas como sslstrip para degradar HTTPS a HTTP, capturando credenciales y tokens de sesión en texto plano.".into(),
                impact: "Robo completo de credenciales. El atacante obtiene acceso autenticado a la aplicación con los permisos de la víctima. Todos los datos transmitidos durante la sesión quedan expuestos.".into(),
                likelihood: "Medio — Requiere proximidad de red (mismo WiFi, ARP spoofing). Común en redes compartidas.".into(),
                severity_class: "High".into(),
            }
        } else {
            AttackScenario {
                title: "Man-in-the-Middle Attack (Network Interception)".into(),
                description: "Without HSTS, the first connection from a user's browser can be intercepted. An attacker on the same network (WiFi, corporate LAN) can use tools like sslstrip to downgrade HTTPS to HTTP, capturing credentials and session tokens in plaintext.".into(),
                impact: "Complete credential theft. Attacker gains authenticated access to the application with the victim's permissions. All data transmitted during the session is exposed.".into(),
                likelihood: "Medium — Requires network proximity (same WiFi, ARP spoofing). Common in shared networks.".into(),
                severity_class: "High".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-1021") && !seen.contains("clickjacking") {
        seen.insert("clickjacking");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Clickjacking (Ataque de Redirección de UI)".into(),
                description: "La aplicación puede ser embebida en un iframe invisible en una página controlada por el atacante. Los usuarios interactúan con lo que creen es un sitio legítimo, pero sus clics se ejecutan en la aplicación embebida — enviando formularios, cambiando configuraciones o autorizando acciones.".into(),
                impact: "Acciones no autorizadas ejecutadas bajo la sesión de la víctima. Recolección de credenciales mediante formularios de login superpuestos.".into(),
                likelihood: "Medio — Requiere ingeniería social para atraer víctimas a la página del atacante.".into(),
                severity_class: "Medium".into(),
            }
        } else {
            AttackScenario {
                title: "Clickjacking (UI Redress Attack)".into(),
                description: "The application can be embedded in an invisible iframe on an attacker-controlled page. Users interact with what they think is a legitimate site, but their clicks are actually performed on the embedded application — submitting forms, changing settings, or authorizing actions.".into(),
                impact: "Unauthorized actions performed under the victim's session. Credential harvesting through overlaid login forms.".into(),
                likelihood: "Medium — Requires social engineering to lure victims to the attacker's page.".into(),
                severity_class: "Medium".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-693") && !seen.contains("xss-csp") {
        seen.insert("xss-csp");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Amplificación de XSS (Sin CSP)".into(),
                description: "Sin Content-Security-Policy, cualquier vulnerabilidad XSS se vuelve significativamente más peligrosa. Scripts inyectados pueden cargar recursos externos, exfiltrar datos a servidores del atacante, registrar teclas y secuestrar sesiones sin restricción del navegador.".into(),
                impact: "Si se encuentra un vector XSS (almacenado o reflejado), el atacante tiene ejecución de scripts sin restricciones. La exfiltración de datos, secuestro de sesión y toma de control de cuentas se vuelven triviales.".into(),
                likelihood: "Bajo-Medio — Requiere un vector XSS, pero la falta de CSP elimina toda mitigación.".into(),
                severity_class: "Medium".into(),
            }
        } else {
            AttackScenario {
                title: "Cross-Site Scripting Amplification (No CSP)".into(),
                description: "Without Content-Security-Policy, any XSS vulnerability becomes significantly more dangerous. Injected scripts can load external resources, exfiltrate data to attacker-controlled servers, keylog input fields, and hijack sessions without any browser restriction.".into(),
                impact: "If an XSS vector is found (stored or reflected), the attacker has unrestricted script execution. Data exfiltration, session hijacking, and full account takeover become trivial.".into(),
                likelihood: "Low-Medium — Requires an XSS vector, but the lack of CSP removes all mitigation.".into(),
                severity_class: "Medium".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-352") && !seen.contains("csrf") {
        seen.insert("csrf");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Cross-Site Request Forgery (Acciones No Autorizadas)".into(),
                description: "Formularios sin protección CSRF permiten a un atacante crear una página maliciosa que envía solicitudes automáticamente en nombre de un usuario autenticado. Visitar la página del atacante mientras está logueado ejecuta acciones que el usuario nunca pretendió.".into(),
                impact: "Cambios de estado no autorizados: restablecimiento de contraseñas, modificaciones de datos, escalamiento de privilegios. Login CSRF puede forzar autenticación con credenciales controladas por el atacante.".into(),
                likelihood: "Medio — Requiere que la víctima visite la página del atacante mientras está autenticada.".into(),
                severity_class: "Medium".into(),
            }
        } else {
            AttackScenario {
                title: "Cross-Site Request Forgery (Unauthorized Actions)".into(),
                description: "Forms without CSRF protection allow an attacker to craft a malicious page that automatically submits requests on behalf of an authenticated user. Visiting the attacker's page while logged in triggers actions the user never intended.".into(),
                impact: "Unauthorized state changes: password resets, data modifications, privilege escalation. Login CSRF can force authentication with attacker-controlled credentials for session monitoring.".into(),
                likelihood: "Medium — Requires victim to visit attacker's page while authenticated.".into(),
                severity_class: "Medium".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-89") && !seen.contains("sqli") {
        seen.insert("sqli");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Compromiso de Base de Datos via Inyección SQL".into(),
                description: "La inyección SQL permite a un atacante ejecutar consultas arbitrarias en la base de datos. Esto puede evadir autenticación, extraer contenidos completos de la base de datos, modificar o eliminar registros, y en algunos casos ejecutar comandos del sistema operativo en el servidor de base de datos.".into(),
                impact: "Compromiso completo de la base de datos. Exfiltración masiva de datos (registros de usuarios, credenciales, datos de negocio). Manipulación o destrucción de datos. Potencial movimiento lateral a sistemas internos.".into(),
                likelihood: "Alto — Herramientas automatizadas pueden explotar inyección SQL con mínimo esfuerzo.".into(),
                severity_class: "Critical".into(),
            }
        } else {
            AttackScenario {
                title: "Database Compromise via SQL Injection".into(),
                description: "SQL injection allows an attacker to execute arbitrary database queries. This can bypass authentication, extract entire database contents, modify or delete records, and in some cases execute operating system commands on the database server.".into(),
                impact: "Complete database compromise. Mass data exfiltration (user records, credentials, business data). Data manipulation or destruction. Potential lateral movement to internal systems.".into(),
                likelihood: "High — Automated tools can exploit SQL injection with minimal effort.".into(),
                severity_class: "Critical".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-79") && !seen.contains("xss") {
        seen.insert("xss");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Toma de Control de Cuenta via Cross-Site Scripting".into(),
                description: "XSS reflejado o almacenado permite a un atacante ejecutar JavaScript en el contexto de las sesiones de otros usuarios. Esto habilita robo de cookies de sesión, registro de teclas de credenciales, desfiguración y redirección a páginas de phishing.".into(),
                impact: "Secuestro de sesión y toma de control de cuentas. XSS almacenado afecta a cada usuario que visualiza la página infectada. Robo de credenciales mediante formularios de login falsos inyectados en la página.".into(),
                likelihood: "Alto — XSS reflejado requiere un enlace manipulado; XSS almacenado afecta a todos los visitantes automáticamente.".into(),
                severity_class: "High".into(),
            }
        } else {
            AttackScenario {
                title: "Account Takeover via Cross-Site Scripting".into(),
                description: "Reflected or stored XSS allows an attacker to execute JavaScript in the context of other users' sessions. This enables session cookie theft, keylogging of credentials, defacement, and redirection to phishing pages.".into(),
                impact: "Session hijacking and account takeover. Stored XSS affects every user who views the infected page. Credential theft through fake login forms injected into the page.".into(),
                likelihood: "High — Reflected XSS requires a crafted link; Stored XSS affects all visitors automatically.".into(),
                severity_class: "High".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-1336") && !seen.contains("ssti") {
        seen.insert("ssti");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Ejecución Remota de Código via Inyección de Plantillas".into(),
                description: "Server-Side Template Injection permite a un atacante inyectar expresiones de plantilla que se evalúan en el servidor. Dependiendo del motor de plantillas, esto puede escalar desde divulgación de información hasta ejecución remota de código completa en el servidor.".into(),
                impact: "Ejecución remota de código en el servidor. Compromiso total del sistema. Acceso a bases de datos internas, sistemas de archivos y recursos de red. Exfiltración de datos a escala.".into(),
                likelihood: "Alto — Una vez identificado, la explotación de SSTI está bien documentada para todos los motores de plantillas principales.".into(),
                severity_class: "Critical".into(),
            }
        } else {
            AttackScenario {
                title: "Remote Code Execution via Template Injection".into(),
                description: "Server-Side Template Injection allows an attacker to inject template expressions that are evaluated on the server. Depending on the template engine, this can escalate from information disclosure to full remote code execution on the server.".into(),
                impact: "Remote code execution on the server. Full system compromise. Access to internal databases, file systems, and network resources. Data exfiltration at scale.".into(),
                likelihood: "High — Once identified, SSTI exploitation is well-documented for all major template engines.".into(),
                severity_class: "Critical".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-78") && !seen.contains("cmdi") {
        seen.insert("cmdi");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Compromiso del Servidor via Inyección de Comandos OS".into(),
                description: "La inyección de comandos permite a un atacante ejecutar comandos arbitrarios del sistema operativo en el servidor. Esto proporciona acceso directo al sistema subyacente, evadiendo todos los controles a nivel de aplicación.".into(),
                impact: "Compromiso completo del servidor. Acceso al sistema de archivos, recolección de credenciales, movimiento lateral a otros sistemas, instalación de backdoors o malware.".into(),
                likelihood: "Alto — La explotación es directa una vez identificado el punto de inyección.".into(),
                severity_class: "Critical".into(),
            }
        } else {
            AttackScenario {
                title: "Server Compromise via OS Command Injection".into(),
                description: "Command injection allows an attacker to execute arbitrary operating system commands on the server. This provides direct access to the underlying system, bypassing all application-level controls.".into(),
                impact: "Complete server compromise. File system access, credential harvesting, lateral movement to other systems, installation of backdoors or malware.".into(),
                likelihood: "High — Exploitation is straightforward once the injection point is identified.".into(),
                severity_class: "Critical".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-200") && !seen.contains("info-disc") {
        seen.insert("info-disc");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Explotación Dirigida via Divulgación de Información".into(),
                description: "Los headers de versión del servidor y las huellas tecnológicas permiten a los atacantes identificar versiones exactas del software ejecutándose en el servidor. Esto habilita búsquedas dirigidas de CVEs conocidos y exploits públicos específicos para las versiones detectadas.".into(),
                impact: "Reduce significativamente el esfuerzo del atacante. En lugar de pruebas a ciegas, el atacante puede usar exploits conocidos para la versión específica detectada.".into(),
                likelihood: "Alto — Scanners automatizados recopilan esta información rutinariamente. Este es frecuentemente el primer paso en un ataque dirigido.".into(),
                severity_class: "Low".into(),
            }
        } else {
            AttackScenario {
                title: "Targeted Exploitation via Information Disclosure".into(),
                description: "Server version headers and technology fingerprints allow attackers to identify exact software versions running on the server. This enables targeted searches for known CVEs and public exploits specific to the detected versions.".into(),
                impact: "Reduces attacker effort significantly. Instead of blind testing, the attacker can use known exploits for the specific version detected.".into(),
                likelihood: "High — Automated scanners routinely collect this information. This is often the first step in a targeted attack.".into(),
                severity_class: "Low".into(),
            }
        });
    }

    if cwes.iter().any(|c| c == "CWE-319") && cwes.iter().any(|c| c == "CWE-352") && !seen.contains("chain-session") {
        seen.insert("chain-session");
        scenarios.push(if is_es {
            AttackScenario {
                title: "Cadena de Ataque: Intercepción de Red + CSRF".into(),
                description: "La combinación de HSTS faltante y vulnerabilidades CSRF crea una cadena de ataque. Un atacante en la red intercepta la conexión HTTP inicial (sin HSTS), inyecta un payload CSRF en la respuesta, y el navegador de la víctima ejecuta acciones no autorizadas con su sesión autenticada.".into(),
                impact: "Impacto combinado: robo de credenciales Y acciones no autorizadas. El atacante tanto roba la sesión como la usa para realizar acciones que la víctima nunca pretendió.".into(),
                likelihood: "Medio — Requiere proximidad de red pero la cadena está bien establecida.".into(),
                severity_class: "High".into(),
            }
        } else {
            AttackScenario {
                title: "Attack Chain: Network Interception + CSRF".into(),
                description: "The combination of missing HSTS and CSRF vulnerabilities creates an attack chain. An attacker on the network intercepts the initial HTTP connection (no HSTS), injects a CSRF payload into the response, and the victim's browser executes unauthorized actions with their authenticated session.".into(),
                impact: "Combined impact: credential theft AND unauthorized actions. The attacker both steals the session and uses it to perform actions the victim never intended.".into(),
                likelihood: "Medium — Requires network proximity but the chain is well-established.".into(),
                severity_class: "High".into(),
            }
        });
    }

    scenarios.sort_by(|a, b| {
        let ord = |s: &str| match s { "Critical" => 0, "High" => 1, "Medium" => 2, _ => 3 };
        ord(&a.severity_class).cmp(&ord(&b.severity_class))
    });

    scenarios
}

/// Generates a prioritized remediation plan from findings
fn generate_remediation_plan(findings: &[Finding], lang: &str) -> Vec<RemediationStep> {
    let mut steps = Vec::new();
    let mut seen_cwes = std::collections::HashSet::new();
    let is_es = lang == "es";

    let mut sorted: Vec<&Finding> = findings.iter().collect();
    sorted.sort_by(|a, b| a.severity.cmp(&b.severity));

    for f in &sorted {
        let cwe = f.cwe_id.as_deref().unwrap_or("");
        if cwe.is_empty() || seen_cwes.contains(cwe) {
            continue;
        }
        seen_cwes.insert(cwe.to_string());

        let (priority, action, effort) = if is_es {
            match cwe {
                "CWE-89" => ("P0 — Bloqueante", "Usar consultas parametrizadas/prepared statements. Revisar todas las consultas a base de datos por concatenación de strings con entrada del usuario.", "Medio"),
                "CWE-79" => ("P0 — Bloqueante", "Implementar codificación de salida según contexto. Desplegar header Content-Security-Policy para restringir ejecución de scripts.", "Medio"),
                "CWE-1336" => ("P0 — Bloqueante", "Nunca pasar entrada del usuario a motores de plantillas. Usar plantillas sandboxed/sin lógica. Validar y sanitizar todo contenido dinámico.", "Medio"),
                "CWE-78" => ("P0 — Bloqueante", "Eliminar construcción de comandos OS desde entrada del usuario. Usar APIs nativas del lenguaje en lugar de comandos de shell.", "Medio"),
                "CWE-319" => ("P1 — Pre-lanzamiento", "Agregar header Strict-Transport-Security: max-age=31536000; includeSubDomains. Configurar redirección HTTPS a nivel de load balancer/proxy.", "Bajo"),
                "CWE-1021" => ("P1 — Pre-lanzamiento", "Agregar header X-Frame-Options: DENY. También agregar frame-ancestors 'none' en CSP como defensa en profundidad.", "Bajo"),
                "CWE-352" => ("P1 — Pre-lanzamiento", "Implementar tokens anti-CSRF en todos los formularios que cambien estado. Usar SameSite=Strict o Lax en cookies de sesión.", "Medio"),
                "CWE-693" => ("P2 — Próximo sprint", "Desplegar headers Content-Security-Policy, X-Content-Type-Options, Referrer-Policy y Permissions-Policy.", "Bajo"),
                "CWE-200" => ("P2 — Próximo sprint", "Remover u ofuscar header Server. Deshabilitar divulgación de versión en la configuración del servidor de aplicación.", "Bajo"),
                "CWE-93" => ("P1 — Pre-lanzamiento", "Eliminar caracteres CRLF (\\r\\n) de toda entrada de usuario reflejada en headers HTTP.", "Bajo"),
                _ => {
                    let action = if f.recommendation.is_empty() { "Revisar y remediar según mejores prácticas de seguridad." } else { &f.recommendation };
                    ("P3 — Backlog", action, "Variable")
                }
            }
        } else {
            match cwe {
                "CWE-89" => ("P0 — Blocker", "Use parameterized queries/prepared statements. Review all database queries for string concatenation with user input.", "Medium"),
                "CWE-79" => ("P0 — Blocker", "Implement context-aware output encoding. Deploy Content-Security-Policy header to restrict script execution.", "Medium"),
                "CWE-1336" => ("P0 — Blocker", "Never pass user input to template engines. Use sandboxed/logic-less templates. Validate and sanitize all dynamic content.", "Medium"),
                "CWE-78" => ("P0 — Blocker", "Eliminate OS command construction from user input. Use language-native APIs instead of shell commands.", "Medium"),
                "CWE-319" => ("P1 — Pre-launch", "Add Strict-Transport-Security header: max-age=31536000; includeSubDomains. Configure HTTPS redirect at load balancer/proxy level.", "Low"),
                "CWE-1021" => ("P1 — Pre-launch", "Add X-Frame-Options: DENY header. Also add frame-ancestors 'none' in CSP for defense in depth.", "Low"),
                "CWE-352" => ("P1 — Pre-launch", "Implement anti-CSRF tokens in all state-changing forms. Use SameSite=Strict or Lax on session cookies.", "Medium"),
                "CWE-693" => ("P2 — Next sprint", "Deploy Content-Security-Policy, X-Content-Type-Options, Referrer-Policy, and Permissions-Policy headers.", "Low"),
                "CWE-200" => ("P2 — Next sprint", "Remove or obfuscate Server header. Disable version disclosure in application server configuration.", "Low"),
                "CWE-93" => ("P1 — Pre-launch", "Strip CRLF characters (\\r\\n) from all user input reflected in HTTP headers.", "Low"),
                _ => {
                    let action = if f.recommendation.is_empty() { "Review and remediate according to security best practices." } else { &f.recommendation };
                    ("P3 — Backlog", action, "Varies")
                }
            }
        };

        let sev_class = format!("{:?}", f.severity);

        steps.push(RemediationStep {
            priority: priority.into(),
            finding: f.title.clone(),
            action: action.into(),
            effort: effort.into(),
            severity_class: sev_class,
        });
    }

    steps
}

/// Generates an HTML report from scan results
pub fn generate(result: &ScanResult, output_path: &Path) -> Result<()> {
    generate_with_lang(result, output_path, "en")
}

/// Generates an HTML report from scan results in the specified language
pub fn generate_with_lang(result: &ScanResult, output_path: &Path, lang: &str) -> Result<()> {
    let template_path = "templates/report.html";
    let template_content =
        std::fs::read_to_string(template_path).unwrap_or_else(|_| default_template().to_string());

    let mut tera = Tera::default();
    tera.add_raw_template("report.html", &template_content)?;

    let mut context = Context::new();
    context.insert("target", &result.target);
    context.insert("scan_id", &result.scan_id);
    context.insert("started_at", &result.started_at.to_rfc3339());
    context.insert(
        "finished_at",
        &result
            .finished_at
            .map(|t| t.to_rfc3339())
            .unwrap_or_else(|| "N/A".to_string()),
    );
    context.insert("findings", &result.findings);
    context.insert("total_requests", &result.total_requests);
    context.insert("modules_executed", &result.modules_executed);
    context.insert(
        "critical_count",
        &result.count_by_severity(&Severity::Critical),
    );
    context.insert("high_count", &result.count_by_severity(&Severity::High));
    context.insert("medium_count", &result.count_by_severity(&Severity::Medium));
    context.insert("low_count", &result.count_by_severity(&Severity::Low));
    context.insert("info_count", &result.count_by_severity(&Severity::Info));
    context.insert("total_findings", &result.findings.len());
    context.insert("version", env!("CARGO_PKG_VERSION"));

    // Executive summary: risk score
    let critical = result.count_by_severity(&Severity::Critical);
    let high = result.count_by_severity(&Severity::High);
    let medium = result.count_by_severity(&Severity::Medium);
    let low = result.count_by_severity(&Severity::Low);
    let info_count = result.count_by_severity(&Severity::Info);
    let risk_score = critical * 10 + high * 5 + medium * 2 + low;
    context.insert("risk_score", &risk_score);

    let risk_level = if critical > 0 {
        "Critical"
    } else if high > 0 {
        "High"
    } else if medium > 0 {
        "Medium"
    } else if low > 0 {
        "Low"
    } else {
        "None"
    };
    context.insert("risk_level", risk_level);

    // Severity distribution for chart bars
    let total = result.findings.len().max(1);
    context.insert("critical_pct", &((critical * 100) / total));
    context.insert("high_pct", &((high * 100) / total));
    context.insert("medium_pct", &((medium * 100) / total));
    context.insert("low_pct", &((low * 100) / total));
    context.insert("info_pct", &((info_count * 100) / total));

    // Findings grouped by category
    let mut by_category: HashMap<String, Vec<&crate::models::Finding>> = HashMap::new();
    for f in &result.findings {
        by_category.entry(f.category.clone()).or_default().push(f);
    }
    let mut categories: Vec<(String, usize)> = by_category
        .iter()
        .map(|(k, v)| (k.clone(), v.len()))
        .collect();
    categories.sort_by(|a, b| b.1.cmp(&a.1));
    context.insert("categories", &categories);

    // Scan duration
    if let Some(finished) = result.finished_at {
        let duration = finished.signed_duration_since(result.started_at);
        let secs = duration.num_seconds();
        let duration_str = if secs >= 60 {
            format!("{}m {}s", secs / 60, secs % 60)
        } else {
            format!("{secs}s")
        };
        context.insert("duration", &duration_str);
    } else {
        context.insert("duration", "N/A");
    }

    // i18n labels
    let labels = ReportLabels::for_lang(lang);
    context.insert("l", &labels);

    // Attack scenarios & remediation plan
    let scenarios = generate_attack_scenarios(&result.findings, lang);
    let remediation = generate_remediation_plan(&result.findings, lang);
    context.insert("attack_scenarios", &scenarios);
    context.insert("has_scenarios", &!scenarios.is_empty());
    context.insert("remediation_plan", &remediation);
    context.insert("has_remediation", &!remediation.is_empty());

    // Diff report
    let has_diff = result.diff.is_some();
    context.insert("has_diff", &has_diff);
    if let Some(ref diff) = result.diff {
        context.insert("new_findings", &diff.new_findings);
        context.insert("resolved_findings", &diff.resolved_findings);
        context.insert("persisting_findings", &diff.persisting_findings);
        context.insert("new_count", &diff.new_findings.len());
        context.insert("resolved_count", &diff.resolved_findings.len());
        context.insert("persisting_count", &diff.persisting_findings.len());
    }

    let rendered = tera.render("report.html", &context)?;
    std::fs::write(output_path, rendered)?;
    info!("HTML report saved to {}", output_path.display());
    Ok(())
}

fn default_template() -> &'static str {
    r##"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Argos Panoptes - Security Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f1f5f9; color: #1e293b; line-height: 1.6; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }

        /* Header */
        .header { background: linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%); color: white; padding: 40px 30px; border-radius: 12px; margin-bottom: 24px; text-align: center; }
        .header h1 { font-size: 2.2em; margin-bottom: 5px; letter-spacing: 2px; }
        .header .subtitle { opacity: 0.8; font-size: 1.1em; }
        .header .meta { opacity: 0.6; margin-top: 15px; font-size: 0.9em; }

        /* Info bar */
        .info-bar { background: white; padding: 15px 25px; border-radius: 10px; margin-bottom: 20px; display: flex; justify-content: space-between; flex-wrap: wrap; gap: 10px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); font-size: 0.9em; color: #64748b; }

        /* Executive Summary */
        .exec-summary { background: white; padding: 25px; border-radius: 10px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .exec-summary h2 { font-size: 1.3em; margin-bottom: 15px; color: #1e293b; }
        .risk-badge { display: inline-block; padding: 6px 20px; border-radius: 25px; color: white; font-weight: 700; font-size: 1em; letter-spacing: 0.5px; }
        .risk-badge.Critical { background: #dc2626; }
        .risk-badge.High { background: #ea580c; }
        .risk-badge.Medium { background: #ca8a04; }
        .risk-badge.Low { background: #2563eb; }
        .risk-badge.None { background: #22c55e; }
        .risk-score { font-size: 2.5em; font-weight: 800; color: #1e293b; margin-right: 15px; vertical-align: middle; }
        .risk-row { display: flex; align-items: center; gap: 15px; margin-bottom: 20px; }

        /* Severity chart */
        .chart-container { margin-top: 15px; }
        .chart-bar-row { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
        .chart-label { width: 70px; font-size: 0.85em; font-weight: 600; text-align: right; }
        .chart-bar-bg { flex: 1; background: #f1f5f9; border-radius: 6px; height: 24px; overflow: hidden; }
        .chart-bar { height: 100%; border-radius: 6px; min-width: 2px; transition: width 0.3s; display: flex; align-items: center; padding-left: 8px; color: white; font-size: 0.75em; font-weight: 600; }
        .chart-bar.critical { background: #dc2626; }
        .chart-bar.high { background: #ea580c; }
        .chart-bar.medium { background: #ca8a04; }
        .chart-bar.low { background: #2563eb; }
        .chart-bar.info { background: #6b7280; }
        .chart-count { width: 30px; font-size: 0.85em; color: #64748b; }

        /* Summary cards */
        .summary { display: grid; grid-template-columns: repeat(5, 1fr); gap: 15px; margin-bottom: 24px; }
        @media (max-width: 768px) { .summary { grid-template-columns: repeat(2, 1fr); } }
        .card { background: white; padding: 25px 15px; border-radius: 10px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-top: 4px solid #e2e8f0; }
        .card .count { font-size: 2.5em; font-weight: 800; }
        .card .label { font-size: 0.85em; text-transform: uppercase; letter-spacing: 1px; margin-top: 5px; opacity: 0.7; }
        .card.critical { border-top-color: #dc2626; } .card.critical .count { color: #dc2626; }
        .card.high { border-top-color: #ea580c; } .card.high .count { color: #ea580c; }
        .card.medium { border-top-color: #ca8a04; } .card.medium .count { color: #ca8a04; }
        .card.low { border-top-color: #2563eb; } .card.low .count { color: #2563eb; }
        .card.info { border-top-color: #6b7280; } .card.info .count { color: #6b7280; }

        /* Categories */
        .categories { background: white; padding: 20px 25px; border-radius: 10px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .categories h3 { font-size: 1.1em; margin-bottom: 12px; }
        .cat-tag { display: inline-block; background: #f1f5f9; padding: 4px 12px; border-radius: 20px; margin: 3px; font-size: 0.85em; color: #475569; }

        /* Section titles */
        .section-title { font-size: 1.4em; font-weight: 700; margin: 24px 0 15px; padding-bottom: 10px; border-bottom: 2px solid #e2e8f0; }

        /* Findings */
        .finding { background: white; padding: 25px; border-radius: 10px; margin-bottom: 15px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-left: 4px solid #e2e8f0; }
        .finding.sev-Critical { border-left-color: #dc2626; }
        .finding.sev-High { border-left-color: #ea580c; }
        .finding.sev-Medium { border-left-color: #ca8a04; }
        .finding.sev-Low { border-left-color: #2563eb; }
        .finding.sev-Info { border-left-color: #6b7280; }
        .finding h3 { margin-bottom: 10px; font-size: 1.1em; }
        .badge { display: inline-block; padding: 2px 10px; border-radius: 20px; color: white; font-size: 0.75em; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; vertical-align: middle; margin-right: 8px; }
        .badge-Critical { background: #dc2626; }
        .badge-High { background: #ea580c; }
        .badge-Medium { background: #ca8a04; }
        .badge-Low { background: #2563eb; }
        .badge-Info { background: #6b7280; }
        .confidence-badge { display: inline-block; padding: 1px 8px; border-radius: 10px; font-size: 0.7em; font-weight: 600; text-transform: uppercase; vertical-align: middle; margin-left: 5px; }
        .conf-Confirmed { background: #dcfce7; color: #166534; }
        .conf-Tentative { background: #fef9c3; color: #854d0e; }
        .conf-Informational { background: #f1f5f9; color: #64748b; }
        .finding p { margin: 8px 0; color: #475569; }
        .finding .label { font-weight: 600; color: #1e293b; }

        /* Collapsible evidence */
        details { margin: 8px 0; }
        details summary { cursor: pointer; font-weight: 600; color: #1e293b; font-size: 0.9em; padding: 5px 0; }
        details summary:hover { color: #3b82f6; }
        pre { background: #f8fafc; border: 1px solid #e2e8f0; padding: 15px; border-radius: 6px; overflow-x: auto; font-size: 0.85em; margin: 8px 0; white-space: pre-wrap; word-wrap: break-word; }
        .meta-info { display: flex; flex-wrap: wrap; gap: 15px; margin-top: 12px; padding-top: 12px; border-top: 1px solid #f1f5f9; font-size: 0.85em; color: #64748b; }

        /* Diff section */
        .diff-section { background: white; padding: 25px; border-radius: 10px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .diff-section h2 { font-size: 1.3em; margin-bottom: 15px; }
        .diff-stats { display: flex; gap: 20px; margin-bottom: 15px; }
        .diff-stat { padding: 8px 16px; border-radius: 8px; font-weight: 600; font-size: 0.9em; }
        .diff-new { background: #fef2f2; color: #dc2626; }
        .diff-resolved { background: #f0fdf4; color: #16a34a; }
        .diff-persisting { background: #fffbeb; color: #ca8a04; }
        .diff-item { padding: 8px 12px; margin: 4px 0; border-radius: 6px; font-size: 0.9em; display: flex; align-items: center; gap: 8px; }
        .diff-item.new { background: #fef2f2; }
        .diff-item.resolved { background: #f0fdf4; }

        /* Attack Scenarios */
        .scenarios-section, .remediation-section { background: white; padding: 25px; border-radius: 10px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .scenarios-section h2, .remediation-section h2 { font-size: 1.3em; margin-bottom: 8px; color: #1e293b; }
        .scenarios-intro, .remediation-intro { color: #64748b; font-size: 0.9em; margin-bottom: 18px; }
        .scenario { border-left: 4px solid #e2e8f0; padding: 15px 20px; margin-bottom: 12px; border-radius: 0 8px 8px 0; background: #f8fafc; }
        .scenario.sev-Critical { border-left-color: #dc2626; background: #fef2f2; }
        .scenario.sev-High { border-left-color: #ea580c; background: #fff7ed; }
        .scenario.sev-Medium { border-left-color: #ca8a04; background: #fffbeb; }
        .scenario.sev-Low { border-left-color: #2563eb; background: #eff6ff; }
        .scenario-header { margin-bottom: 10px; font-size: 1.05em; }
        .scenario-body p { color: #475569; margin-bottom: 10px; font-size: 0.92em; }
        .scenario-detail { display: flex; gap: 8px; margin-top: 6px; font-size: 0.88em; color: #64748b; }
        .scenario-detail .label { font-weight: 600; color: #1e293b; min-width: 85px; }

        /* Remediation Table */
        .remediation-table { width: 100%; border-collapse: collapse; font-size: 0.9em; margin-top: 10px; }
        .remediation-table th { background: #f1f5f9; padding: 10px 12px; text-align: left; font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; border-bottom: 2px solid #e2e8f0; }
        .remediation-table td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
        .rem-row.rem-Critical td { background: #fef2f2; }
        .rem-row.rem-High td { background: #fff7ed; }
        .rem-row.rem-Medium td { background: #fffbeb; }
        .priority-badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.8em; font-weight: 600; white-space: nowrap; }
        .priority-P0 { background: #dc2626; color: white; }
        .priority-P1 { background: #ea580c; color: white; }
        .priority-P2 { background: #ca8a04; color: white; }
        .priority-P3 { background: #6b7280; color: white; }

        /* Footer */
        .footer { text-align: center; padding: 30px; color: #94a3b8; font-size: 0.85em; margin-top: 30px; }

        /* Print styles */
        @media print {
            body { background: white; }
            .container { max-width: 100%; padding: 10px; }
            .header { background: #1e293b !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .card, .finding, .exec-summary, .diff-section, .categories, .info-bar { box-shadow: none; border: 1px solid #e2e8f0; }
            .chart-bar { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .badge, .risk-badge, .confidence-badge { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            details { open; }
            details[open] summary { display: none; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>&#128305; ARGOS PANOPTES</h1>
            <div class="subtitle">{{ l.subtitle }}</div>
            <div class="meta">Target: {{ target }} | Scan ID: {{ scan_id }}</div>
        </div>

        <div class="info-bar">
            <span><strong>{{ l.started }}</strong> {{ started_at }}</span>
            <span><strong>{{ l.finished }}</strong> {{ finished_at }}</span>
            <span><strong>{{ l.duration_label }}</strong> {{ duration }}</span>
            <span><strong>{{ l.requests }}</strong> {{ total_requests }}</span>
            <span><strong>{{ l.modules_label }}</strong> {{ modules_executed | join(sep=", ") }}</span>
        </div>

        <!-- Executive Summary -->
        <div class="exec-summary">
            <h2>{{ l.executive_summary }}</h2>
            <div class="risk-row">
                <span class="risk-score">{{ risk_score }}</span>
                <span class="risk-badge {{ risk_level }}">{{ risk_level }} {{ l.risk_suffix }}</span>
            </div>
            <div class="chart-container">
                <div class="chart-bar-row">
                    <span class="chart-label">{{ l.critical }}</span>
                    <div class="chart-bar-bg"><div class="chart-bar critical" style="width: {{ critical_pct }}%">{% if critical_count > 0 %}{{ critical_count }}{% endif %}</div></div>
                    <span class="chart-count">{{ critical_count }}</span>
                </div>
                <div class="chart-bar-row">
                    <span class="chart-label">{{ l.high }}</span>
                    <div class="chart-bar-bg"><div class="chart-bar high" style="width: {{ high_pct }}%">{% if high_count > 0 %}{{ high_count }}{% endif %}</div></div>
                    <span class="chart-count">{{ high_count }}</span>
                </div>
                <div class="chart-bar-row">
                    <span class="chart-label">{{ l.medium }}</span>
                    <div class="chart-bar-bg"><div class="chart-bar medium" style="width: {{ medium_pct }}%">{% if medium_count > 0 %}{{ medium_count }}{% endif %}</div></div>
                    <span class="chart-count">{{ medium_count }}</span>
                </div>
                <div class="chart-bar-row">
                    <span class="chart-label">{{ l.low }}</span>
                    <div class="chart-bar-bg"><div class="chart-bar low" style="width: {{ low_pct }}%">{% if low_count > 0 %}{{ low_count }}{% endif %}</div></div>
                    <span class="chart-count">{{ low_count }}</span>
                </div>
                <div class="chart-bar-row">
                    <span class="chart-label">{{ l.info_label }}</span>
                    <div class="chart-bar-bg"><div class="chart-bar info" style="width: {{ info_pct }}%">{% if info_count > 0 %}{{ info_count }}{% endif %}</div></div>
                    <span class="chart-count">{{ info_count }}</span>
                </div>
            </div>
        </div>

        <div class="summary">
            <div class="card critical"><div class="count">{{ critical_count }}</div><div class="label">{{ l.critical }}</div></div>
            <div class="card high"><div class="count">{{ high_count }}</div><div class="label">{{ l.high }}</div></div>
            <div class="card medium"><div class="count">{{ medium_count }}</div><div class="label">{{ l.medium }}</div></div>
            <div class="card low"><div class="count">{{ low_count }}</div><div class="label">{{ l.low }}</div></div>
            <div class="card info"><div class="count">{{ info_count }}</div><div class="label">{{ l.info_label }}</div></div>
        </div>

        {% if categories | length > 0 %}
        <div class="categories">
            <h3>{{ l.findings_by_category }}</h3>
            {% for cat in categories %}
            <span class="cat-tag">{{ cat.0 }} ({{ cat.1 }})</span>
            {% endfor %}
        </div>
        {% endif %}

        {% if has_scenarios %}
        <div class="scenarios-section">
            <h2>{{ l.attack_scenarios }}</h2>
            <p class="scenarios-intro">{{ l.attack_scenarios_intro }}</p>
            {% for scenario in attack_scenarios %}
            <div class="scenario sev-{{ scenario.severity_class }}">
                <div class="scenario-header">
                    <span class="badge badge-{{ scenario.severity_class }}">{{ scenario.severity_class }}</span>
                    <strong>{{ scenario.title }}</strong>
                </div>
                <div class="scenario-body">
                    <p>{{ scenario.description }}</p>
                    <div class="scenario-detail">
                        <span class="label">{{ l.impact_label }}</span>
                        <span>{{ scenario.impact }}</span>
                    </div>
                    <div class="scenario-detail">
                        <span class="label">{{ l.likelihood_label }}</span>
                        <span>{{ scenario.likelihood }}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}

        {% if has_remediation %}
        <div class="remediation-section">
            <h2>{{ l.remediation_plan }}</h2>
            <p class="remediation-intro">{{ l.remediation_intro }}</p>
            <table class="remediation-table">
                <thead>
                    <tr>
                        <th>{{ l.priority }}</th>
                        <th>{{ l.finding_label }}</th>
                        <th>{{ l.action_required }}</th>
                        <th>{{ l.effort }}</th>
                    </tr>
                </thead>
                <tbody>
                {% for step in remediation_plan %}
                    <tr class="rem-row rem-{{ step.severity_class }}">
                        <td><span class="priority-badge priority-{{ step.priority | truncate(length=2, end="") | trim }}">{{ step.priority }}</span></td>
                        <td>{{ step.finding }}</td>
                        <td>{{ step.action }}</td>
                        <td>{{ step.effort }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}

        {% if has_diff %}
        <div class="diff-section">
            <h2>{{ l.differential_analysis }}</h2>
            <div class="diff-stats">
                <span class="diff-stat diff-new">+{{ new_count }} {{ l.new_label }}</span>
                <span class="diff-stat diff-resolved">-{{ resolved_count }} {{ l.resolved_label }}</span>
                <span class="diff-stat diff-persisting">={{ persisting_count }} {{ l.persisting_label }}</span>
            </div>
            {% if new_count > 0 %}
            <h4 style="color: #dc2626; margin: 10px 0 5px;">{{ l.new_findings_regressions }}</h4>
            {% for f in new_findings %}
            <div class="diff-item new">
                <span class="badge badge-{{ f.severity }}">{{ f.severity }}</span>
                <span>{{ f.title }}</span>
                <span style="color: #94a3b8; margin-left: auto; font-size: 0.85em;">{{ f.url }}</span>
            </div>
            {% endfor %}
            {% endif %}
            {% if resolved_count > 0 %}
            <h4 style="color: #16a34a; margin: 10px 0 5px;">{{ l.resolved_findings_fixed }}</h4>
            {% for f in resolved_findings %}
            <div class="diff-item resolved">
                <span class="badge badge-{{ f.severity }}">{{ f.severity }}</span>
                <span>{{ f.title }}</span>
                <span style="color: #94a3b8; margin-left: auto; font-size: 0.85em;">{{ f.url }}</span>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        {% endif %}

        <div class="section-title">{{ l.findings_title }} ({{ total_findings }})</div>
        {% for finding in findings %}
        <div class="finding sev-{{ finding.severity }}">
            <h3>
                <span class="badge badge-{{ finding.severity }}">{{ finding.severity }}</span>
                {{ finding.title }}
                <span class="confidence-badge conf-{{ finding.confidence }}">{{ finding.confidence }}</span>
            </h3>
            <p>{{ finding.description }}</p>
            {% if finding.evidence %}
            <details>
                <summary>{{ l.evidence }}</summary>
                <pre>{{ finding.evidence }}</pre>
            </details>
            {% endif %}
            {% if finding.request %}
            <details>
                <summary>{{ l.request_label }}</summary>
                <pre>{{ finding.request }}</pre>
            </details>
            {% endif %}
            {% if finding.response %}
            <details>
                <summary>{{ l.response_label }}</summary>
                <pre>{{ finding.response }}</pre>
            </details>
            {% endif %}
            {% if finding.recommendation %}<p><span class="label">{{ l.recommendation }}</span> {{ finding.recommendation }}</p>{% endif %}
            <div class="meta-info">
                {% if finding.cwe_id %}<span>{{ finding.cwe_id }}</span>{% endif %}
                {% if finding.owasp_category %}<span>{{ finding.owasp_category }}</span>{% endif %}
                <span>{{ finding.url }}</span>
            </div>
        </div>
        {% endfor %}
        {% if total_findings == 0 %}
        <div class="finding"><h3>{{ l.no_findings }}</h3><p>{{ l.no_findings_desc }}</p></div>
        {% endif %}
        <div class="footer">{{ l.generated_by }} v{{ version }} | {{ started_at }}</div>
    </div>
</body>
</html>"##
}
